Back Propogation using Pytorch

y = x^2

In [1]:
import torch

In [2]:
x = torch.tensor(4.0, requires_grad=True)

In [3]:
x

tensor(4., requires_grad=True)

In [5]:
y = x**2
y

tensor(16., grad_fn=<PowBackward0>)

In [6]:
# Back propogation y = 2*x
y.backward()

In [7]:
print(x.grad)

tensor(8.)


In [17]:
lst = [[2.,3.,4.], [4.,5.,6.], [7.,6.,4.]]

torch_input = torch.tensor(lst, requires_grad=True)

In [18]:
torch_input

tensor([[2., 3., 4.],
        [4., 5., 6.],
        [7., 6., 4.]], requires_grad=True)

In [19]:
y = torch_input**3+torch_input**2

In [20]:
y

tensor([[ 12.,  36.,  80.],
        [ 80., 150., 252.],
        [392., 252.,  80.]], grad_fn=<AddBackward0>)

In [21]:
z = y.sum()

In [24]:
z

tensor(1334., grad_fn=<SumBackward0>)

In [25]:
z.backward()

In [26]:
torch_input.grad

tensor([[ 16.,  33.,  56.],
        [ 56.,  85., 120.],
        [161., 120.,  56.]])