In [1]:
import torch

In [2]:
torch.__version__

'2.4.1+cpu'

In [3]:
import numpy as np

In [4]:
lst = [2,3,4,5]
arr = np.array(lst)

In [5]:
arr.dtype

dtype('int64')

Convert Numpy to Pytorch tensors

In [7]:
tensors = torch.from_numpy(arr)
tensors

tensor([2, 3, 4, 5])

In [9]:
tensors.dtype

torch.int64

In [10]:
tensors[:2]

tensor([2, 3])

In [11]:
tensors[1:3]

tensor([3, 4])

In [12]:
tensors[3] = 100

In [13]:
tensors

tensor([  2,   3,   4, 100])

In [14]:
arr

array([  2,   3,   4, 100])

In [15]:
## Prent this by using torch.tensor
tensor_arr = torch.tensor(arr)
tensor_arr

tensor([  2,   3,   4, 100])

In [16]:
tensor_arr[3] = 200

In [17]:
tensor_arr

tensor([  2,   3,   4, 200])

In [18]:
arr

array([  2,   3,   4, 100])

In [20]:
torch.zeros(2, 3, dtype=torch.float64)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [21]:
torch.ones(2,3,dtype=torch.float16)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float16)

In [24]:
np.arange(0,15).reshape(3, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [26]:
a = torch.tensor(np.arange(0,15).reshape(5,3))

In [27]:
a

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

In [28]:
a[:, 1]

tensor([ 1,  4,  7, 10, 13])

Arithmetic Operation

In [29]:
a = torch.tensor([2,3,4], dtype=torch.float)
b = torch.tensor([2,1,3], dtype=torch.float)
print(a+b)

tensor([4., 4., 7.])


In [30]:
torch.add(a,b)

tensor([4., 4., 7.])

In [31]:
c = torch.zeros(3)

In [32]:
c

tensor([0., 0., 0.])

In [33]:
torch.add(a, b, out=c)

tensor([4., 4., 7.])

In [34]:
torch.add(a, b).sum()

tensor(15.)

Dot Products and Multi Operations

In [38]:
x = torch.tensor([1,2,3], dtype=torch.float)
y = torch.tensor([3,4,5], dtype=torch.float)

In [39]:
x.mul(y)

tensor([ 3.,  8., 15.])

In [40]:
x.dot(y)

tensor(26.)

In [41]:
# Matrix Multiplication

In [50]:
x = torch.tensor([[1,2,3], [4,5,6]], dtype=torch.float)
y = torch.tensor([[5,6], [3,4], [1,2]], dtype=torch.float)

In [51]:
torch.matmul(x,y)

tensor([[14., 20.],
        [41., 56.]])

In [52]:
torch.mm(x,y)

tensor([[14., 20.],
        [41., 56.]])

In [53]:
x@y

tensor([[14., 20.],
        [41., 56.]])