In [3]:
import torch
import numpy as np

In [5]:
torch.cuda.is_available()

False

In [6]:
some_data = [[1,2], [3, 4]]

In [7]:
some_data

[[1, 2], [3, 4]]

In [8]:
type(some_data)

list

In [9]:
np.array(some_data)

array([[1, 2],
       [3, 4]])

In [10]:
np.asarray(some_data)

array([[1, 2],
       [3, 4]])

In [12]:
some_data = torch.tensor(some_data)

In [13]:
type(some_data)

torch.Tensor

In [14]:
some_data.dtype

torch.int64

In [15]:
numpy_array = np.random.rand(3,4)

In [16]:
numpy_array

array([[0.94879738, 0.89478978, 0.24618004, 0.65830105],
       [0.72595834, 0.02194062, 0.75283125, 0.88318738],
       [0.08767664, 0.39069738, 0.40583861, 0.03664323]])

In [17]:
torch.from_numpy(numpy_array)

tensor([[0.9488, 0.8948, 0.2462, 0.6583],
        [0.7260, 0.0219, 0.7528, 0.8832],
        [0.0877, 0.3907, 0.4058, 0.0366]], dtype=torch.float64)

In [18]:
torch.tensor(numpy_array)

tensor([[0.9488, 0.8948, 0.2462, 0.6583],
        [0.7260, 0.0219, 0.7528, 0.8832],
        [0.0877, 0.3907, 0.4058, 0.0366]], dtype=torch.float64)

In [19]:
torch.ones(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
torch.zeros(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
torch.rand(3,4)

tensor([[0.1117, 0.1742, 0.1115, 0.0793],
        [0.3784, 0.9398, 0.6209, 0.2525],
        [0.6775, 0.9606, 0.5284, 0.9071]])

In [22]:
my_tensor = torch.rand(3,4)

In [23]:
my_tensor.dtype

torch.float32

In [24]:
my_tensor.device

device(type='cpu')

In [27]:
# my_tensor.to("cuda")
# my_tensor = my_tensor.to("cuda")

In [28]:
my_tensor[:, 1:3]

tensor([[0.7580, 0.0770],
        [0.6239, 0.6543],
        [0.8037, 0.2447]])

In [29]:
my_tensor.mul(my_tensor)

tensor([[0.2010, 0.5746, 0.0059, 0.0310],
        [0.0780, 0.3892, 0.4281, 0.0011],
        [0.7176, 0.6459, 0.0599, 0.5814]])

In [30]:
my_tensor * my_tensor

tensor([[0.2010, 0.5746, 0.0059, 0.0310],
        [0.0780, 0.3892, 0.4281, 0.0011],
        [0.7176, 0.6459, 0.0599, 0.5814]])

In [32]:
my_tensor.matmul(my_tensor.T)

tensor([[0.8125, 0.6544, 1.1421],
        [0.6544, 0.8964, 0.9236],
        [1.1421, 0.9236, 2.0047]])

In [33]:
torch.matmul(my_tensor, my_tensor.T)

tensor([[0.8125, 0.6544, 1.1421],
        [0.6544, 0.8964, 0.9236],
        [1.1421, 0.9236, 2.0047]])

In [35]:
my_tensor @ my_tensor.T

tensor([[0.8125, 0.6544, 1.1421],
        [0.6544, 0.8964, 0.9236],
        [1.1421, 0.9236, 2.0047]])

In [36]:
my_tensor.sum()

tensor(5.7083)

In [37]:
my_tensor.sum(axis=1)

tensor([1.4594, 1.5909, 2.6580])

In [38]:
# torch.max, torch.min

In [40]:
torch.cat([my_tensor, my_tensor])

tensor([[0.4483, 0.7580, 0.0770, 0.1761],
        [0.2792, 0.6239, 0.6543, 0.0336],
        [0.8471, 0.8037, 0.2447, 0.7625],
        [0.4483, 0.7580, 0.0770, 0.1761],
        [0.2792, 0.6239, 0.6543, 0.0336],
        [0.8471, 0.8037, 0.2447, 0.7625]])

In [42]:
torch.cat([my_tensor, my_tensor], axis=1)
# torch.cat([my_tensor, my_tensor], dim=1)


tensor([[0.4483, 0.7580, 0.0770, 0.1761, 0.4483, 0.7580, 0.0770, 0.1761],
        [0.2792, 0.6239, 0.6543, 0.0336, 0.2792, 0.6239, 0.6543, 0.0336],
        [0.8471, 0.8037, 0.2447, 0.7625, 0.8471, 0.8037, 0.2447, 0.7625]])

In [44]:
my_tensor

tensor([[0.4483, 0.7580, 0.0770, 0.1761],
        [0.2792, 0.6239, 0.6543, 0.0336],
        [0.8471, 0.8037, 0.2447, 0.7625]])

In [43]:
torch.nn.functional.softmax(my_tensor, dim=1)

tensor([[0.2622, 0.3573, 0.1808, 0.1997],
        [0.2151, 0.3036, 0.3130, 0.1683],
        [0.2921, 0.2796, 0.1599, 0.2684]])

In [46]:
torch.nn.functional.softmax(my_tensor, dim=0)

tensor([[0.2999, 0.3423, 0.2523, 0.2729],
        [0.2532, 0.2994, 0.4494, 0.2366],
        [0.4469, 0.3583, 0.2984, 0.4905]])

In [47]:
my_tensor.shape

torch.Size([3, 4])

In [48]:
my_tensor.size()

torch.Size([3, 4])

In [49]:
my_tensor.size()[1]

4

In [50]:
# 10 -> Batch size, 3 -> no of channels, 128, 128 -> image width and height
torch.rand(10, 3, 128, 128)

tensor([[[[8.9982e-01, 9.4285e-01, 7.7945e-02,  ..., 4.5431e-01,
           1.1518e-01, 2.8151e-01],
          [9.1014e-01, 2.5449e-01, 2.3238e-01,  ..., 5.9213e-01,
           8.8869e-01, 1.1276e-01],
          [6.4573e-01, 3.7433e-01, 5.0916e-01,  ..., 8.0527e-01,
           5.6795e-01, 8.7214e-01],
          ...,
          [1.0492e-01, 2.3322e-01, 4.3459e-01,  ..., 6.5166e-01,
           1.8782e-01, 5.0753e-01],
          [4.9301e-01, 9.0072e-01, 5.6279e-01,  ..., 3.2460e-01,
           6.4834e-01, 6.3211e-01],
          [8.9624e-01, 8.5826e-01, 5.7957e-01,  ..., 7.6280e-01,
           8.6849e-01, 3.3041e-01]],

         [[2.4665e-01, 6.4405e-01, 5.8757e-01,  ..., 9.8014e-02,
           7.9276e-02, 7.3217e-01],
          [5.6036e-01, 4.4311e-01, 1.2250e-01,  ..., 4.0430e-01,
           8.5714e-01, 7.7864e-01],
          [6.9022e-01, 2.4362e-01, 5.8308e-01,  ..., 3.8385e-01,
           8.2269e-01, 4.1911e-01],
          ...,
          [7.8645e-01, 9.3483e-01, 4.0956e-03,  ..., 6.9612

In [51]:
torch.rand(10, 3, 128, 128).size()

torch.Size([10, 3, 128, 128])

In [52]:
my_tensor.clip(0.2, 0.8)

tensor([[0.4483, 0.7580, 0.2000, 0.2000],
        [0.2792, 0.6239, 0.6543, 0.2000],
        [0.8000, 0.8000, 0.2447, 0.7625]])

In [54]:
# From tensor to numpy array
my_tensor.cpu().detach().numpy()

array([[0.4483139 , 0.7580285 , 0.07699257, 0.17608094],
       [0.2792107 , 0.62388355, 0.654262  , 0.0335716 ],
       [0.84708434, 0.8036536 , 0.24472791, 0.76252323]], dtype=float32)