Autograd is automatic deferentiation engine in PyTorch

In [1]:
import torch

In [2]:
a = torch.tensor([5.], requires_grad=True)
b = torch.tensor([6.], requires_grad=True)

In [3]:
a

tensor([5.], requires_grad=True)

In [4]:
b

tensor([6.], requires_grad=True)

In [5]:
y = a**3 - b**2

In [6]:
y

tensor([89.], grad_fn=<SubBackward0>)

In [7]:
# dy/da = 3*a**2 => 3*25 -> 75
# dy/db = -2b = -12

In [10]:
print(a.grad)
print(b.grad)

None
None


In [11]:
y.backward()

In [13]:
a.grad

tensor([75.])

In [12]:
print(a.grad)
print(b.grad)

tensor([75.])
tensor([-12.])


In [15]:
w = torch.randn(10, 1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

In [16]:
w

tensor([[-0.9069],
        [ 0.0845],
        [ 2.3424],
        [-0.1228],
        [-1.7118],
        [ 0.2625],
        [ 1.1590],
        [-0.0052],
        [-0.5628],
        [ 0.8643]], requires_grad=True)

In [17]:
b

tensor([-0.2944], requires_grad=True)

In [18]:
x = torch.rand(1, 10)

In [19]:
x

tensor([[1.5607e-01, 7.1428e-01, 5.8636e-01, 5.7851e-01, 8.6373e-01, 7.6628e-04,
         5.1380e-01, 8.4989e-01, 9.0562e-01, 8.9168e-01]])

In [20]:
output = torch.matmul(x, w) + b

In [21]:
loss = 1 - output

In [22]:
loss

tensor([[0.6995]], grad_fn=<RsubBackward1>)

In [23]:
 loss.backward()

In [24]:
w.grad

tensor([[-1.5607e-01],
        [-7.1428e-01],
        [-5.8636e-01],
        [-5.7851e-01],
        [-8.6373e-01],
        [-7.6628e-04],
        [-5.1380e-01],
        [-8.4989e-01],
        [-9.0562e-01],
        [-8.9168e-01]])

In [26]:
w.grad.data

tensor([[-1.5607e-01],
        [-7.1428e-01],
        [-5.8636e-01],
        [-5.7851e-01],
        [-8.6373e-01],
        [-7.6628e-04],
        [-5.1380e-01],
        [-8.4989e-01],
        [-9.0562e-01],
        [-8.9168e-01]])

In [25]:
b.grad

tensor([-1.])

In [27]:
with torch.no_grad():
    w = w - 0.001 * w.grad.data

In [28]:
w

tensor([[-0.9068],
        [ 0.0852],
        [ 2.3430],
        [-0.1223],
        [-1.7110],
        [ 0.2625],
        [ 1.1595],
        [-0.0044],
        [-0.5619],
        [ 0.8652]])