In [1]:
import torch

In [ ]:
# nn.Module  -> Base class of all nn module

Containers

- Module
- Sequential
- ModelList
- ModelDict

Layers:

- Conv1d , Conv2d
- MaxPool1d, MaxPool2d
- AvgPool1d, AvgPool2d
- BatchNorm1d, BatchNorm2d
- LayerNorm
- LSTM , GRU, 
- Linear, Dropout, Embedding, Transformer

Activations

- ReLU
- LeakyReLU
- Sigmoid
- Tanh
- Softmax

Loss Functions

- MSELoss  -> MeansquaredError
- CrossEntropyLoss
- NLLLoss  -> 
- BCELoss  -> Binary Cross Entropy Loss
- BCEWithLogitsLoss  -> Binary Cross Entropy with

In [2]:
import torch
import torch.nn as nn

In [3]:
class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.layer1 = nn.Linear(128, 32)
        self.layer2 = nn.Linear(32, 16)
        self.layer3 = nn.Linear(16, 1)

    def forward(self, features):
        # (32, 128) -> 32 is the batch_sizw
        x = self.layer1(features)
        # (32, 32)
        x = self.layer2(x)
        x = self.layer3(x)
        # (32, 1)
        return x

In [6]:
model = Model()

features = torch.rand(2, 128)
print(features)

tensor([[0.8405, 0.0343, 0.6214, 0.7671, 0.6541, 0.7500, 0.2187, 0.3493, 0.1278,
         0.8938, 0.4095, 0.8046, 0.8922, 0.2412, 0.9289, 0.3744, 0.7673, 0.3742,
         0.3575, 0.9705, 0.0401, 0.6170, 0.6682, 0.8882, 0.2638, 0.9103, 0.4588,
         0.6888, 0.2993, 0.4081, 0.7506, 0.0522, 0.9874, 0.1218, 0.1047, 0.9440,
         0.5672, 0.7175, 0.3329, 0.7843, 0.2966, 0.1599, 0.9389, 0.9134, 0.7652,
         0.6329, 0.5535, 0.9246, 0.0863, 0.8663, 0.1768, 0.0604, 0.7917, 0.7263,
         0.9164, 0.0961, 0.5096, 0.4710, 0.1253, 0.7827, 0.1339, 0.3688, 0.9804,
         0.9095, 0.4889, 0.7433, 0.5424, 0.6907, 0.5912, 0.9734, 0.4859, 0.6705,
         0.5911, 0.4852, 0.7882, 0.6868, 0.1916, 0.9519, 0.8811, 0.2780, 0.1598,
         0.4705, 0.0089, 0.1022, 0.8973, 0.7982, 0.3800, 0.8264, 0.0815, 0.2548,
         0.0014, 0.2785, 0.6472, 0.8606, 0.3262, 0.1013, 0.0150, 0.6738, 0.8384,
         0.8554, 0.6489, 0.3668, 0.0726, 0.0888, 0.6105, 0.4896, 0.8166, 0.8925,
         0.8045, 0.8759, 0.1

In [7]:
features.shape

torch.Size([2, 128])

In [8]:
model(features)

tensor([[-0.1235],
        [-0.0069]], grad_fn=<AddmmBackward0>)

In [9]:
features.device

device(type='cpu')

In [11]:
features = features.to("cpu")
model = Model()
model.to("cpu")
model(features)

tensor([[-0.1052],
        [-0.2962]], grad_fn=<AddmmBackward0>)

In [13]:
class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.base = nn.Sequential(
            nn.Linear(128, 32),
            nn.Linear(32, 16),
            nn.Linear(16, 1),
        )

    def forward(self, features):
        x = self.base(features)
        return x

In [14]:
features = features.to("cpu")
model = Model()
model.to("cpu")
model(features)

tensor([[0.2987],
        [0.2726]], grad_fn=<AddmmBackward0>)